name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.11'
          - 'pre'
        os:
          - ubuntu-latest
          - windows-latest
        arch:
          - x64
        include:
          # macos-latest runners are Apple Silicon, which only supports aarch64
          - os: macos-latest
            arch: aarch64
            version: '1.11'
          - os: macos-latest
            arch: aarch64
            version: 'pre'
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - name: Install Zenity (Ubuntu only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update && sudo apt-get install -y zenity
          which zenity
      - uses: julia-actions/julia-runtest@v1
